# Generated by Django 4.2 on 2023-08-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cell',
            new_name='Activity_cell',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='district',
            new_name='Activity_district',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='province',
            new_name='Activity_province',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='sector',
            new_name='Activity_sector',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='village',
            new_name='Activity_village',
        ),
    ]
