# Generated by Django 4.2 on 2023-08-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_service_userid_service_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='Mining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='Preciselaborsavingoperations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='Signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='aerialPhotographyCheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='aerialSprayingCheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='aerialSurveyCheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='ndviCheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='orthophotoCheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='otherInformationCheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='photographyandvideography',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='roundwithprecisionagriculture',
            field=models.BooleanField(default=False),
        ),
    ]
