# Generated by Django 4.2 on 2023-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_service_mapping_alter_service_mining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Signature',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
