# Generated by Django 4.2 on 2023-08-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_phone_alter_customer_contact_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
