# Generated by Django 4.2 on 2023-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
