# Generated by Django 4.2 on 2023-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_service_status_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='DescriptionoftheActivity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='LocationofTheActivity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
