# Generated by Django 4.2 on 2023-09-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_service_descriptionoftheactivity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='request_date',
            new_name='BusinessType',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='service',
            new_name='DateHappened',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='customer',
            new_name='District',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ApprovedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='TaskActivityDetails',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='TinNumber',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customerNationalId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='serviceLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='serviceName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
