# Generated by Django 4.2 on 2023-09-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rename_request_date_servicerequest_businesstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='BusinessType',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
