# Generated by Django 4.2 on 2023-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_customuser_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalanalysis',
            old_name='service_request',
            new_name='nationalId',
        ),
        migrations.RemoveField(
            model_name='technicalanalysis',
            name='feasibility',
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='businessCategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='dateHappened',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysis',
            name='searchTIN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
