# Generated by Django 4.2 on 2023-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_rename_service_request_technicalanalysis_nationalid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalanalysis',
            name='analysis_date',
        ),
        migrations.AlterField(
            model_name='technicalanalysis',
            name='nationalId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
